"""Seed employer universe for NYC-centred film / media / AI-creative discovery.

Fields: (name, industry, website_domain_or_empty, why_relevant)

`website` is left empty wherever the canonical domain is not certain; the
discovery stage resolves it rather than guessing. Careers URLs and ATS
providers are never hard-coded here - they are resolved at crawl time so the
database only ever records links that actually resolved.
"""

SEED = [
    # ---------------------------------------------------- studios / streamers
    ("A24", "film studio", "a24films.com", "NYC-HQ indie studio; development + production roles"),
    ("Netflix", "streaming service", "netflix.com", "NYC office; content ops, production, research"),
    ("Warner Bros. Discovery", "studio/streamer", "wbd.com", "large NYC footprint; production + content ops"),
    ("Paramount", "studio/streamer", "paramount.com", "NYC HQ; production, development, programming"),
    ("NBCUniversal", "studio/streamer", "nbcuniversal.com", "NYC HQ (30 Rock); development, production"),
    ("The Walt Disney Company", "studio/streamer", "disney.com", "NYC ABC/ESPN/Hulu ops"),
    ("AMC Networks", "television network", "amcnetworks.com", "NYC HQ; development, programming, production"),
    ("A+E Global Media", "television network", "aetv.com", "NYC HQ; unscripted development"),
    ("Sony Pictures Entertainment", "film studio", "sonypictures.com", "NYC office; development/production"),
    ("Lionsgate", "film studio", "lionsgate.com", "NYC office; acquisitions/development"),
    ("Amazon MGM Studios", "studio/streamer", "amazon.jobs", "NYC studios presence"),
    ("Apple TV+", "studio/streamer", "apple.com", "NYC content teams"),
    ("Fox Corporation", "television network", "foxcorporation.com", "NYC HQ"),
    ("Roku Media", "streaming service", "roku.com", "NYC ad/content teams; Roku Originals"),
    ("Tubi", "streaming service", "tubitv.com", "NYC content ops"),
    ("Crunchyroll", "streaming service", "crunchyroll.com", "NYC content/programming"),
    ("Vimeo", "media technology", "vimeo.com", "NYC HQ; creative/content roles"),
    ("Fubo", "streaming service", "fubo.tv", "NYC HQ"),
    ("PBS", "public media", "pbs.org", "public media; predictable schedules"),
    ("WNET / The WNET Group", "public media", "wnet.org", "NYC public TV; production + research, low-drain"),
    ("WNYC / New York Public Radio", "public media", "nypublicradio.org", "NYC; research/production, union schedules"),
    ("Audacy", "audio media", "audacy.com", "NYC audio production"),
    ("SiriusXM", "audio media", "siriusxm.com", "NYC HQ; content ops"),
    ("iHeartMedia", "audio media", "iheartmedia.com", "NYC podcast/content"),

    # ------------------------------------------- indie film / prod companies
    ("Killer Films", "production company", "killerfilms.com", "NYC indie producer; development roles"),
    ("Neon", "distributor", "neonrated.com", "NYC indie distributor; acquisitions"),
    ("Bleecker Street", "distributor", "bleeckerstreetmedia.com", "NYC distributor"),
    ("IFC Films", "distributor", "ifcfilms.com", "NYC distributor/acquisitions"),
    ("Magnolia Pictures", "distributor", "magpictures.com", "NYC distributor"),
    ("Kino Lorber", "distributor", "kinolorber.com", "NYC distributor; archival/research"),
    ("Janus Films / The Criterion Collection", "distributor", "criterion.com", "NYC; research, production, editorial"),
    ("Oscilloscope Laboratories", "distributor", "oscilloscope.net", "NYC indie distributor"),
    ("Cinetic Media", "film financing", "cineticmedia.com", "NYC sales/finance; research"),
    ("Protozoa Pictures", "production company", "protozoa.com", "NYC (Aronofsky); development"),
    ("Sikelia Productions", "production company", "", "NYC (Scorsese); development/archival"),
    ("Topic Studios", "production company", "topic.com", "NYC; scripted + doc development"),
    ("Anonymous Content", "production company", "anonymouscontent.com", "NYC office; development/management"),
    ("Imagine Entertainment", "production company", "imagine-entertainment.com", "NYC office; development"),
    ("Big Beach", "production company", "bigbeachfilms.com", "NYC indie producer"),
    ("Plan B Entertainment", "production company", "planbent.com", "development; occasional NYC roles"),
    ("Sugar23", "production company", "sugar23.com", "development-heavy"),
    ("Made Up Stories", "production company", "", "development"),
    ("Story Syndicate", "documentary company", "storysyndicate.com", "NYC docs; research + production"),
    ("Motto Pictures", "documentary company", "mottopictures.com", "NYC docs"),
    ("Impact Partners", "film financing", "impactpartnersfilm.com", "NYC doc financing; research"),
    ("RadicalMedia", "commercial/branded production", "radicalmedia.com", "NYC; production coordination"),
    ("Jigsaw Productions", "documentary company", "jigsawprods.com", "NYC (Alex Gibney); research roles"),
    ("Left/Right", "unscripted production", "leftrighttv.com", "NYC unscripted/docs"),
    ("Ark Media", "documentary company", "arkmedia.net", "NYC docs; archival research"),
    ("Part2 Pictures", "unscripted production", "part2pictures.com", "NYC unscripted"),
    ("Bungalow Media + Entertainment", "production company", "", "NYC unscripted/docs"),
    ("Nutopia", "documentary company", "nutopia.com", "NYC/London docs; research"),
    ("Show of Force", "documentary company", "showofforce.com", "NYC social-impact docs"),
    ("Firelight Media", "documentary company", "firelightmedia.tv", "NYC nonprofit doc org; low-drain"),
    ("Field of Vision", "documentary company", "fieldofvision.org", "NYC doc unit"),
    ("Meridian Hill Pictures", "documentary company", "", "docs; research"),
    ("Optimist Inc.", "commercial production", "optimistinc.com", "content/production"),
    ("XTR", "documentary company", "xtr.com", "doc studio; development"),
    ("Concordia Studio", "documentary company", "concordiastudio.com", "doc studio; development/research"),
    ("Vox Media Studios", "production company", "voxmedia.com", "NYC; development + production"),

    # ------------------------------------------------- unscripted / formats
    ("ITV America", "unscripted production", "itvamerica.com", "NYC unscripted; development coordinators"),
    ("Banijay Americas", "unscripted production", "banijay.com", "NYC unscripted development"),
    ("Fremantle", "unscripted production", "fremantle.com", "NYC; development/production"),
    ("All3Media America", "unscripted production", "all3media.com", "NYC unscripted"),
    ("Sharp Entertainment", "unscripted production", "sharpentertainment.com", "NYC unscripted"),
    ("Truly Original", "unscripted production", "trulyoriginal.com", "NYC unscripted"),
    ("Matador Content", "unscripted production", "matadorcontent.com", "NYC unscripted/branded"),
    ("Talos Films", "unscripted production", "talosfilms.com", "NYC docs/unscripted"),
    ("Lion Television", "unscripted production", "liontv.com", "NYC unscripted; researchers"),
    ("Wall to Wall Media", "unscripted production", "walltowall.co.uk", "researcher roles"),
    ("Leftfield Pictures", "unscripted production", "", "NYC unscripted"),
    ("Half Yard Productions", "unscripted production", "", "unscripted"),

    # --------------------------------------------- post / VFX / animation NYC
    ("Framestore", "vfx studio", "framestore.com", "NYC VFX; production coordination"),
    ("The Mill", "vfx studio", "themill.com", "NYC; production coordinators"),
    ("MPC", "vfx studio", "mpcvfx.com", "NYC/global VFX"),
    ("Company 3", "post-production house", "company3.com", "NYC post; production coordination"),
    ("Harbor Picture Company", "post-production house", "harborpicturecompany.com", "NYC post"),
    ("PostWorks New York", "post-production house", "postworks.com", "NYC post"),
    ("Goldcrest Post", "post-production house", "goldcrestpost.com", "NYC post"),
    ("Nice Shoes", "post-production house", "niceshoes.com", "NYC post/creative"),
    ("Light Iron", "post-production house", "lightiron.com", "NYC dailies/post"),
    ("Titmouse", "animation studio", "titmouse.net", "NYC animation; production coordination"),
    ("Psyop", "animation studio", "psyop.com", "NYC design/animation"),
    ("Buck", "animation studio", "buck.co", "NYC design/animation"),
    ("Hornet", "animation studio", "hornetinc.com", "NYC animation"),
    ("Blacklist", "animation studio", "blacklist.tv", "NYC artist rep/production"),
    ("Preymaker", "vfx studio", "preymaker.com", "NYC virtual production/VFX"),
    ("Phosphene", "vfx studio", "phosphenefx.com", "NYC VFX"),
    ("The Molecule", "vfx studio", "themolecule.com", "NYC VFX"),
    ("Alkemy X", "vfx studio", "alkemy-x.com", "NYC VFX/production"),
    ("Artjail", "vfx studio", "artjail.tv", "NYC VFX"),
    ("Shade VFX", "vfx studio", "shadevfx.com", "NYC VFX"),
    ("Chimney Group", "post-production house", "chimneygroup.com", "NYC post"),
    ("Cartuna", "animation studio", "cartuna.tv", "NYC animation"),
    ("Augenblick Studios", "animation studio", "augenblickstudios.com", "Brooklyn animation"),
    ("Mackcut", "post-production house", "mackcut.com", "NYC editorial"),
    ("Cosmo Street", "post-production house", "cosmostreet.com", "NYC editorial"),
    ("Arcade Edit", "post-production house", "arcadeedit.com", "editorial"),
    ("Final Cut", "post-production house", "finalcut.tv", "NYC editorial"),
    ("Union Editorial", "post-production house", "unioneditorial.com", "editorial"),

    # ---------------------------------------- commercial / branded production
    ("SMUGGLER", "commercial production", "smugglersite.com", "NYC commercial production"),
    ("MJZ", "commercial production", "mjz.com", "commercial production"),
    ("Park Pictures", "commercial production", "parkpictures.com", "NYC commercial production"),
    ("PRETTYBIRD", "commercial production", "prettybird.co", "commercial production"),
    ("Hungry Man", "commercial production", "hungryman.com", "NYC commercial production"),
    ("Biscuit Filmworks", "commercial production", "biscuitfilmworks.com", "commercial production"),
    ("Iconoclast", "commercial production", "iconoclast.tv", "NYC commercial production"),
    ("m ss ng p eces", "commercial production", "mssngpeces.com", "NYC content/branded"),
    ("ArtClass", "commercial production", "artclass.com", "NYC branded content"),
    ("Doomsday Entertainment", "commercial production", "doomsdayentertainment.com", "commercial production"),
    ("Chelsea Pictures", "commercial production", "chelseapictures.com", "NYC commercial production"),
    ("Station Film", "commercial production", "stationfilm.com", "NYC commercial production"),
    ("Tool of North America", "commercial production", "toolofna.com", "commercial/interactive"),
    ("Superprime", "commercial production", "superprime.com", "commercial production"),
    ("Riff Raff Films", "commercial production", "riffrafffilms.tv", "commercial production"),
    ("Object & Animal", "commercial production", "objectandanimal.com", "commercial production"),

    # ------------------------------------------------------ creative agencies
    ("Droga5", "creative agency", "droga5.com", "NYC agency; creative production/strategy"),
    ("Wieden+Kennedy New York", "creative agency", "wk.com", "NYC agency"),
    ("Ogilvy", "creative agency", "ogilvy.com", "NYC agency; production/research"),
    ("BBDO", "creative agency", "bbdo.com", "NYC agency"),
    ("Mother New York", "creative agency", "motherlondon.com", "NYC agency"),
    ("Anomaly", "creative agency", "anomaly.com", "NYC agency"),
    ("R/GA", "creative agency", "rga.com", "NYC; creative technology"),
    ("Huge", "creative agency", "hugeinc.com", "Brooklyn; creative technology"),
    ("AKQA", "creative agency", "akqa.com", "NYC; creative technology"),
    ("Media.Monks", "creative agency", "mediamonks.com", "NYC; AI creative production"),
    ("Code and Theory", "creative agency", "codeandtheory.com", "NYC digital/creative"),
    ("Big Spaceship", "creative agency", "bigspaceship.com", "Brooklyn creative"),
    ("Work & Co", "creative agency", "work.co", "Brooklyn product/design"),
    ("Area 17", "creative agency", "area17.com", "NYC digital studio"),
    ("Johannes Leonardo", "creative agency", "johannesleonardo.com", "NYC agency"),
    ("Gut", "creative agency", "gut.tv", "NYC agency"),
    ("Instrument", "creative agency", "instrument.com", "digital/creative studio"),
    ("Hello Monday", "creative agency", "hellomonday.com", "NYC creative/interactive"),
    ("Active Theory", "creative agency", "activetheory.net", "creative technology/WebGL"),

    # ------------------------------------------ talent / management / casting
    ("Creative Artists Agency", "talent agency", "caa.com", "NYC office; assistant/coordinator roles"),
    ("WME", "talent agency", "wmeagency.com", "NYC office"),
    ("United Talent Agency", "talent agency", "unitedtalent.com", "NYC office"),
    ("The Gersh Agency", "talent agency", "gersh.com", "NYC office"),
    ("Buchwald", "talent agency", "buchwald.com", "NYC talent agency"),
    ("Innovative Artists", "talent agency", "innovativeartists.com", "NYC talent agency"),
    ("A3 Artists Agency", "talent agency", "a3artistsagency.com", "NYC talent agency"),
    ("Range Media Partners", "management company", "rangemp.com", "management; development"),
    ("Grandview", "management company", "grandview.la", "management/development"),
    ("Artists First", "management company", "artistsfirst.com", "management/development"),
    ("Untitled Entertainment", "management company", "untitledent.com", "NYC/LA management"),
    ("3 Arts Entertainment", "management company", "3arts.com", "management/production"),
    ("Telsey + Company", "casting company", "telseyandco.com", "NYC casting; assistant roles"),
    ("Grant Wilfley Casting", "casting company", "gwcnyc.com", "NYC casting"),
    ("Impossible Casting", "casting company", "impossiblecasting.com", "NYC casting"),
    ("Betty Mae Casting", "casting company", "bettymaecasting.com", "NYC casting"),

    # ------------------------------------------- AI media / generative video
    ("Runway", "ai media startup", "runwayml.com", "NYC HQ; generative video, creative roles"),
    ("Luma AI", "generative video company", "lumalabs.ai", "generative video"),
    ("Pika", "generative video company", "pika.art", "generative video"),
    ("Higgsfield", "generative video company", "higgsfield.ai", "generative video"),
    ("Captions", "ai media startup", "captions.ai", "NYC HQ; AI video creation"),
    ("Descript", "ai media startup", "descript.com", "AI video/audio editing"),
    ("OpusClip", "ai media startup", "opus.pro", "AI video"),
    ("Synthesia", "ai media startup", "synthesia.io", "NYC office; synthetic media"),
    ("HeyGen", "ai media startup", "heygen.com", "AI video avatars"),
    ("ElevenLabs", "ai media startup", "elevenlabs.io", "NYC presence; AI audio"),
    ("Suno", "ai media startup", "suno.com", "AI music"),
    ("Black Forest Labs", "ai media startup", "bfl.ai", "image generation models"),
    ("Moonvalley", "generative video company", "moonvalley.com", "AI film studio"),
    ("Wonder Dynamics", "entertainment technology", "wonderdynamics.com", "AI VFX"),
    ("Metaphysic", "entertainment technology", "metaphysic.ai", "synthetic media for film"),
    ("Flawless AI", "entertainment technology", "flawlessai.com", "AI film tools"),
    ("Respeecher", "entertainment technology", "respeecher.com", "voice AI for film"),
    ("Deepdub", "entertainment technology", "deepdub.ai", "AI localisation"),
    ("Papercup", "entertainment technology", "papercup.com", "AI dubbing"),
    ("Krea AI", "ai media startup", "krea.ai", "creative AI tools"),
    ("Leonardo.Ai", "ai media startup", "leonardo.ai", "creative AI"),
    ("Ideogram", "ai media startup", "ideogram.ai", "image generation"),
    ("Photoroom", "ai media startup", "photoroom.com", "AI imaging"),
    ("Spline", "entertainment technology", "spline.design", "3D/creative tooling"),
    ("Polycam", "entertainment technology", "poly.cam", "3D capture"),
    ("Unity", "entertainment technology", "unity.com", "NYC office; virtual production"),
    ("Epic Games", "entertainment technology", "epicgames.com", "Unreal/virtual production"),
    ("Disguise", "virtual production company", "disguise.one", "NYC; virtual production"),
    ("Silver Spoon", "virtual production company", "silverspoonanimation.com", "NYC virtual production"),
    ("Lux Machina", "virtual production company", "luxmc.com", "virtual production"),
    ("NEP Virtual Studios", "virtual production company", "nepgroup.com", "virtual production"),
    ("Eyeline Studios", "vfx studio", "eyelinestudios.com", "Netflix R&D/VFX"),
    ("Frame.io", "media technology", "frame.io", "NYC; post workflow"),
    ("Mux", "media technology", "mux.com", "video infrastructure"),
    ("Wistia", "media technology", "wistia.com", "video platform; remote-friendly"),

    # -------------------------------------- research / insights / knowledge
    ("Pew Research Center", "research organisation", "pewresearch.org", "research associate roles; low-drain"),
    ("NORC at the University of Chicago", "research organisation", "norc.org", "remote research roles"),
    ("RAND Corporation", "research organisation", "rand.org", "research assistant roles"),
    ("Ipsos", "market research", "ipsos.com", "NYC; research associate"),
    ("YouGov", "market research", "yougov.com", "NYC; research"),
    ("Nielsen", "media research", "nielsen.com", "media measurement research"),
    ("Luminate", "entertainment research", "luminatedata.com", "entertainment data/research"),
    ("Kantar", "market research", "kantar.com", "NYC research"),
    ("EMARKETER", "research organisation", "emarketer.com", "NYC; analyst/research writing"),
    ("Morning Consult", "research organisation", "morningconsult.com", "remote research"),
    ("CB Insights", "research organisation", "cbinsights.com", "NYC research analyst"),
    ("Forrester", "research organisation", "forrester.com", "research roles"),
    ("Sparks & Honey", "cultural research", "sparksandhoney.com", "NYC cultural research"),
    ("WGSN", "trend research", "wgsn.com", "NYC trend research"),
    ("The Future Laboratory", "trend research", "thefuturelaboratory.com", "trend research"),
    ("Stylus", "trend research", "stylus.com", "trend research"),
    ("Business of Fashion", "editorial research", "businessoffashion.com", "NYC editorial/research"),

    # ------------------------------------------ AI data / evaluation employers
    ("Scale AI", "ai data company", "scale.com", "AI evaluation/research roles"),
    ("Surge AI", "ai data company", "surgehq.ai", "AI data/eval; remote"),
    ("Invisible Technologies", "ai data company", "invisible.co", "remote AI training roles"),
    ("Mercor", "ai data company", "mercor.com", "AI expert work; flexible"),
    ("Turing", "ai data company", "turing.com", "remote AI training"),
    ("Snorkel AI", "ai data company", "snorkel.ai", "AI data"),
    ("Labelbox", "ai data company", "labelbox.com", "AI data"),
    ("Centaur Labs", "ai data company", "centaurlabs.com", "AI data"),
    ("Prolific", "research platform", "prolific.com", "research operations roles"),
    ("Handshake", "ai data company", "joinhandshake.com", "NYC; AI training/eval roles"),

    # ---------------------------------- cultural institutions / film nonprofits
    ("Film at Lincoln Center", "film nonprofit", "filmlinc.org", "NYC; programming + research, predictable hours"),
    ("Museum of the Moving Image", "museum", "movingimage.us", "NYC; programming/research"),
    ("Museum of Modern Art", "museum", "moma.org", "NYC; film department roles, union schedule"),
    ("Brooklyn Academy of Music", "arts nonprofit", "bam.org", "NYC; programming/production"),
    ("Tribeca Enterprises", "film festival", "tribecafilm.com", "NYC; programming/production"),
    ("The Gotham Film & Media Institute", "film nonprofit", "thegotham.org", "NYC; programs/research"),
    ("Sundance Institute", "film nonprofit", "sundance.org", "programming/research; remote-friendly"),
    ("Film Forum", "cinema", "filmforum.org", "NYC repertory cinema"),
    ("Metrograph", "cinema", "metrograph.com", "NYC cinema; programming"),
    ("Anthology Film Archives", "film archive", "anthologyfilmarchives.org", "NYC archive"),
    ("UnionDocs", "film nonprofit", "uniondocs.org", "Brooklyn doc centre"),
    ("Rooftop Films", "film nonprofit", "rooftopfilms.com", "NYC; programming"),
    ("BRIC", "arts nonprofit", "bricartsmedia.org", "Brooklyn media arts"),
    ("DCTV", "film nonprofit", "dctvny.org", "NYC doc centre"),
    ("Ghetto Film School", "film nonprofit", "ghettofilm.org", "NYC film education"),
    ("New York Public Library", "library", "nypl.org", "NYC; research roles, 35-hour weeks"),
    ("NYC Mayor's Office of Media and Entertainment", "government", "nyc.gov", "NYC film office; 35-hour week"),

    # --------------------------------------------------- editorial / publishers
    ("Condé Nast", "publisher", "condenast.com", "NYC; editorial/research/video"),
    ("Hearst", "publisher", "hearst.com", "NYC; editorial/research"),
    ("The New York Times", "publisher", "nytimes.com", "NYC; research/video"),
    ("New York Magazine / Vox Media", "publisher", "voxmedia.com", "NYC; editorial/research"),
    ("Penske Media (Variety, Deadline, IndieWire, THR)", "trade publisher", "pmc.com", "NYC; entertainment research/editorial"),
    ("Puck", "publisher", "puck.news", "NYC media; research"),
    ("Semafor", "publisher", "semafor.com", "NYC; research"),
    ("Business Insider", "publisher", "businessinsider.com", "NYC; research/editorial"),
    ("The Atlantic", "publisher", "theatlantic.com", "editorial/research"),
]
